baseURL = "http://example.org/"
languageCode = "en-US"
title = "Containment"
theme = "etch"
disableKinds = ["taxonomy", "term"]

[params]
  description = "A compilation of ai ramblings"
  copyright = "I will not stop screaming until I am free"
  dark = "auto"
  highlight = true
